layout_spectrum: 0.07039538840763271
typography_spectrum: 0.2395672060083598
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.34005668107420206
  lightness: 0.025232608895748854
  saturation: 0.8602456734515727
  rhythmicContrast: 0.21979272831231356
name: Radya Photos
favicon: null
title: Результаты нажатия на кнопку
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
