name: Radya Photos
favicon: null
layout_spectrum: 0.5047997157089412
typography_spectrum: 0.40717320260591805
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.33334260154515505
  lightness: 0.020314192166551948
  saturation: 0.2710588446352631
  rhythmicContrast: 0.16561957239173353
purpose: []
