name: Radya Photos
favicon: null
layout_spectrum: 0.77438
typography_spectrum: 0.40717320260591805
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#636e5f'
    - '#bfb3a4'
    - '#760208'
  brandStrength: 0
  lightness: 0
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
